services:
  frontend:
    volumes:
      - ./frontend/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/npht:/etc/nginx/certs:ro
      - npht-config:/run/config:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  npht-config:
