name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/DHBWxNPHT_Digitaler-Nationalpark
          git pull
      - name: Deploy
        run: |
          cd ~/DHBWxNPHT_Digitaler-Nationalpark
          docker compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
          docker wait npht-setup
          docker compose logs setup --no-log-prefix --tail 20
